### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by ballenwillis** [vitalcode/auth-graphiql#14]
I'm unsure if I'm just not understanding what exactly you want in the URL text field, but through using GraphiQL I ran my mutation to authenticate a user and get back a JWT. I then copied that JWT into the token field.

My GraphQL endpoint is: http://localhost:5000/graphql so that's what I put in the URL. Is this what is expected?

When I use that as the enpoint, I get the errer: "TypeError: Failed to fetch" and I'm unsure why. If it matters, I'm using PostgraphQL. Any ideas?

**Comment by vitalcode** [comment]
Try http://localhost:5000

**Comment by ballenwillis** [comment]
No luck. As you can see, these are the GraphQL endpoints:

![image](https://user-images.githubusercontent.com/14190965/33000928-6df22d8c-cd70-11e7-97fe-fad5a0c7779f.png)

And, here's a screen shot of me using the authenticate GraphiQL tool you've created to make a basic query given a token targeting that endpoint.

![image](https://user-images.githubusercontent.com/14190965/33000980-c91a7d2c-cd70-11e7-879b-f415f8ed0ca7.png)

Not sure if I'm doing something wrong or whatnot, but graphiql at the endpoint "http://localhost:5000/graphiql" works fine so I'm not sure what's wrong. I've tried with the forward slash on the end, without it, put it in quotes, and just a lot of possibilities with no luck. Thank you for your quick response by the way.

**Comment by vitalcode** [comment]
This could be a CORS issue. Could you open the browser network monitor and check the request error?

**Comment by ballenwillis** [comment]
![image](https://user-images.githubusercontent.com/14190965/33233655-eb8455b4-d1de-11e7-8027-d82769e6c9a9.png)

It does appear to be a CORS issue.

[EDIT] To be clear, I have only heard of CORS. I have no idea what it is.

**Comment by vitalcode** [comment]
You can run PostgraphQL with CORS enabled. See here for cli options: https://github.com/postgraphql/postgraphql/blob/master/src/postgraphql/cli.ts

**Comment by ballenwillis** [comment]
Yep! Problem solved. I'm going to look into CORS so I understand what I'm enabling here. Thanks!
