### ISSUE TITLE
Add versions to docker image @ hub.docker.com

### ISSUE THREAD

**Issue by freiit** [vitalcode/auth-graphiql#8]
I think it would be helpful to have a docker image tag beside "latest" on the build.
What do you think about the current graphiql version + an internal counter.

The current version would be vitalcode/auth-graphiql:0.11.3-1

And while "latest" is rebuild every time something changes on the repository, these old tags and images stay.

**Comment by vitalcode** [comment]
agree

**Comment by vitalcode** [comment]
vitalcode/auth-graphiql:0.3.0 is puplished
